esphome:
  name: victron-test
  friendly_name: Victron Test

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "npdYjSW/NyY/FADwtdVMquyBNk6a2bDzN3jfc0H2lG0="

ota:
  password: "4d1184ab67c87e9041e112a37ea76e1a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Victron-Test Fallback Hotspot"
    password: "qGKeaa3MVOxc"

captive_portal:

uart:
  baud_rate: 19200
  tx_pin: D8
  rx_pin: D7
  debug:
    direction: BOTH
    dummy_receiver: true
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);

#Fake-SmartSolar-MPPT
interval:
  - interval: 3s
    then:
      - uart.write: "PID\t0xA061\r\n"
      - uart.write: "FW\t156\r\n"
      - uart.write: "SER#\tHQ1942K7LJ8\r\n"
      - uart.write: "V\t12450\r\n"
      - uart.write: "I\t0\r\n"
      - uart.write: "VPV\t10\r\n"
      - uart.write: "PPV\t0\r\n"
      - uart.write: "CS\t0\r\n"
      - uart.write: "MPPT\t0\r\n"
      - uart.write: "OR\t0x00000001\r\n"
      - uart.write: "ERR\t0\r\n"
      - uart.write: "LOAD\tON\r\n"
      - uart.write: "IL\t0\r\n"
      - uart.write: "H19\t3\r\n"
      - uart.write: "H20\t0\r\n"
      - uart.write: "H21\t24\r\n"
      - uart.write: "H22\t1\r\n"
      - uart.write: "H23\t15\r\n"
      - uart.write: "HSDS\t3\r\n"
      - uart.write: "Checksum\t\xE1"
      - uart.write: "\r\n"
