esphome:
  name: victron-debug
  platform: ESP8266
  board: d1_mini

external_components:
  - source: github://Martian-Dylan3/Victron_ESPHome@main
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
api:

logger:
  baud_rate: 0
  esp8266_store_log_strings_in_flash: false

uart:
  id: uart_0
  baud_rate: 19200
  tx_pin: D7  # Not connected! The communication is read-only
  rx_pin: D8  # Connect this this GPIO and GND to the MPPT charger
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);

victron:
  uart_id: uart_0
  id: victron0
  throttle: 10s

text_sensor:
  - platform: victron
    victron_id: victron0
    model_description:
      name: "Victron-Debug model description"
    firmware_version:
      name: "Victron-Debug} firmware version"
    device_type:
      name: "Victron-Debug device type"
    serial_number:
      name: "Victron-Debug serial number"
