esphome:
  name: victron-debug

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: github://Martian-Dylan3/Victron_ESPHome@main
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
api:
logger:

uart:
  id: uart_0
  baud_rate: 19200
  tx_pin: GPIO16
  rx_pin: GPIO17
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);

victron:
  uart_id: uart_0
  id: victron0
  #throttle: 10s

text_sensor:
  - platform: victron
    victron_id: victron0
    model_description:
      name: "Victron-Debug Model Description"
    firmware_version:
      name: "Victron-Debug Firmware Version"
    device_type:
      name: "Victron-Debug Device Type"
    serial_number:
      name: "Victron-Debug Serial Number"
