substitutions: 
  name: Multi-RS

esphome:
  name: multi-rs
  platform: ESP8266
  board: d1_mini

external_components:
  - source: github://Martian-Dylan3/Victron_ESPHome@main
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
api:
logger:

uart:
  id: uart_0
  tx_pin: D7  # Not connected! The communication is read-only
  rx_pin: D8
  baud_rate: 19200
  stop_bits: 1
  data_bits: 8
  parity: NONE
  rx_buffer_size: 256

victron:
  uart_id: uart_0
  id: victron0
  #throttle: 10s

sensor:
  - platform: victron
    victron_id: victron0
    charging_mode_id:
      name: "${name} Charging Mode ID"
    error_code:
      name: "${name} Error Code"
    ac_out_current:
      name: "${name} AC Out Current"
      id: ac_current
    ac_out_voltage:
      name: "${name} AC Out Voltage"
      id: ac_voltage
    yield_total:
      name: "${name} Yield Total"
    yield_today:
      name: "${name} Yield Today"
    max_power_today:
      name: "${name} Max Power Today"
    yield_yesterday:
      name: "${name} Yield Yesterday"
    max_power_yesterday:
      name: "${name} Max Power Yesterday"
    day_number:
      name: "${name} Day Number"
    battery_current:
      name: "${name} Battery Current"
    panel_power:
      name: "${name} Panel Power"
    battery_voltage:
      name: "${name} Battery Voltage"
    panel_voltage:
      name: "${name} Panel Voltage"

  - platform: template
    name: "${name} AC Out Power"
    # https://github.com/esphome/issues/issues/2793#issuecomment-988257209
    lambda: |-
       auto val = id(ac_voltage).state * id(ac_current).state;
       if (isnan(val))
          return {};
       return val;
    update_interval: 10s

text_sensor:
  - platform: victron
    victron_id: victron0
    device_type:
      name: "${name} Device Type"
    serial_number:
      name: "${name} Serial Number"
    firmware_version_24bit:
      name: "${name} Firmware Version 24bit"
    charging_mode:
      name: "${name} Charging Mode"
    error:
      name: "${name} Error"
    device_mode:
      name: "${name} Device Mode"
