esphome:
  name: multi-rs
  platform: ESP8266
  board: d1_mini

external_components:
  - source: github://Martian-Dylan3/Victron_ESPHome@main
  refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
api:
logger:

uart:
  id: uart_bus
  tx_pin: D7  # Not connected! The communication is read-only
  rx_pin: D8
  baud_rate: 19200
  stop_bits: 1
  data_bits: 8
  parity: NONE
  rx_buffer_size: 256

victron:
  uart_id: uart_0
  id: victron0
  throttle: 10s

sensor:
  - platform: victron
    victron_id: victron0
    charging_mode_id:
      name: "Multi-RS Charging Mode ID"
    error_code:
      name: "Multi-RS Error Code"
    ac_out_current:
      name: "Multi-RS AC Out Current"
      id: ac_current
    ac_out_voltage:
      name: "Multi-RS AC Out Voltage"
      id: ac_voltage
    yield_total:
      name: "Multi-RS Yield Total"
    yield_today:
      name: "Multi-RS Yield Today"
    max_power_today:
      name: "Multi-RS Max Power Today"
    yield_yesterday:
      name: "Multi-RS Yield Yesterday"
    max_power_yesterday:
      name: "Multi-RS Max Power Yesterday"
    day_number:
      name: "Multi-RS Day Number"
    battery_current:
      name: "Multi-RS Battery Current"
    panel_power:
      name: "Multi-RS Panel Power"
    battery_voltage:
      name: "Multi-RS Battery Voltage"
    panel_voltage:
      name: "Multi-RS Panel Voltage"

  - platform: template
    name: "Multi-RS AC Out Power"
    # https://github.com/esphome/issues/issues/2793#issuecomment-988257209
    lambda: |-
       auto val = id(ac_voltage).state * id(ac_current).state;
       if (isnan(val))
          return {};
       return val;
    update_interval: 10s

text_sensor:
  - platform: victron
    victron_id: victron0
    device_type:
      name: "Multi-RS Device Type"
    serial_number:
      name: "Multi-RS Serial Number"
    firmware_version_24bit:
      name: "Multi-RS Firmware Version 24bit"
    charging_mode:
      name: "Multi-RS Charging Mode"
    error:
      name: "Multi-RS Error"
    device_mode:
      name: "Multi-RS Device Mode"
