substitutions: 
  name: Phoenix-Inverter

esphome:
  name: phoenix-inverter
  platform: ESP8266
  board: d1_mini

external_components:
  - source: github://Martian-Dylan3/Victron_ESPHome@main
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
api:
logger:

uart:
  id: uart_0
  tx_pin: D7  # Not connected! The communication is read-only
  rx_pin: D8
  baud_rate: 19200
  stop_bits: 1
  data_bits: 8
  parity: NONE
  rx_buffer_size: 256

victron:
  uart_id: uart_0
  id: victron0
  #throttle: 10s

sensor:
  - platform: victron
    victron_id: victron0
    battery_voltage:
      name: "${name} Battery Voltage"
    battery_current:
      name: "${name} Battery Current"
    charging_mode_id:
      name: "${name} Charging Mode ID"
    device_mode_id:
      name: "${name} device Mode ID"
    ac_out_voltage:
      name: "${name} AC Out voltage"
    ac_out_current:
      name: "${name} AC Out Current"
    ac_out_apparent_power:
      name: "${name} AC Out Apparent Power"
    warning_code:
      name: "${name} Warning Code"
    off_reason_bitmask:
      name: "${name} Off Reason Bitmask"

text_sensor:
  - platform: victron
    victron_id: victron0
    alarm_reason:
      name: "${name} Alarm Reason"
    charging_mode:
      name: "${name} Charging Mode"
    firmware_version:
      name: "${name} Firmware Version"
    device_type:
      name: "${name} Device Type"
    serial_number:
      name: "${name} Serial Number"
    device_mode:
      name: "${name} Wevice Mode"
    warning:
      name: "${name} Warning"
    off_reason:
      name: "${name} Off Reason"

binary_sensor:
  - platform: victron
    victron_id: victron0
    relay_state:
      name: "${name} Relay State"
