esphome:
  name: phoenix-charger
  platform: ESP8266
  board: d1_mini
  
external_components:
  - source: github://Martian-Dylan3/Victron_ESPHome@main
  refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
api:
logger:

uart:
  id: uart_bus
  tx_pin: D7  # Not connected! The communication is read-only
  rx_pin: D8  # Connect this this GPIO and GND to the MPPT charger
  baud_rate: 19200
  stop_bits: 1
  data_bits: 8
  parity: NONE
  rx_buffer_size: 256

victron:
  uart_id: uart_0
  id: victron0
  throttle: 10s

sensor:
  - platform: victron
    victron_id: victron0
    battery_voltage:
      name: "Phoenix-Charger Battery Voltage"
    battery_voltage_2:
      name: "Phoenix-Charger Battery Voltage 2"
    battery_voltage_3:
      name: "Phoenix-Charger Battery Voltage 3"
    battery_current:
      name: "Phoenix-Charger Battery Current"
    battery_current_2:
      name: "Phoenix-Charger Battery Current 2"
    battery_current_3:
      name: "Phoenix-Charger Battery Current 3"
    error_code:
      name: "Phoenix-Charger Error Code"
    charging_mode_id:
      name: "Phoenix-Charger Charging Mode ID"
    device_mode_id:
      name: "Phoenix-Charger Device Mode ID"

text_sensor:
  - platform: victron
    victron_id: victron0
    error:
      name: "Phoenix-Charger Error"
    charging_mode:
      name: "Phoenix-Charger Charging Mode"
    device_type:
      name: "Phoenix-Charger Device Type"
    serial_number:
      name: "Phoenix-Charger Serial Number"
    device_mode:
      name: "Phoenix-Charger Device Mode"

binary_sensor:
  - platform: victron
    victron_id: victron0
    relay_state:
      name: "Phoenix-Charger Relay State"
