substitutions: 
  name: Victron-MPPT

esphome:
  name: victron-mppt
  platform: ESP8266
  board: d1_mini

external_components:
  - source: github://Martian-Dylan3/Victron_ESPHome@main
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
api:
logger:

uart:
  id: uart_0
  tx_pin: D7  # Not connected! The communication is read-only
  rx_pin: D8
  baud_rate: 19200
  rx_buffer_size: 256

victron:
  uart_id: uart_0
  id: victron0
  throttle: 10s

sensor:
  - platform: victron
    victron_id: victron0
    max_power_yesterday:
      name: "${name} Max Power Yesterday"
    max_power_today:
      name: "${name} Max Power Today"
    yield_total:
      name: "${name} Yield Total"
    yield_yesterday:
      name: "${name} Yield Yesterday"
    yield_today:
      name: "${name} Yield Today"
    panel_voltage:
      name: "${name} Panel Voltage"
    panel_power:
      name: "${name} Panel Power"
    battery_current:
      name: "${name} Panel Current"
    battery_voltage:
      name: "${name} Battery Voltage"
    day_number:
      name: "${name} Day Number"
    charging_mode_id:
      name: "${name} Charging Mode ID"
    error_code:
      name: "${name} Error Code"
    tracking_mode_id:
      name: "${name} Tracking Mode ID"
    load_current:
      name: "${name} Load Current"

text_sensor:
  - platform: victron
    victron_id: victron0
    charging_mode:
      name: "${name} Charging Mode"
    error:
      name: "${name} Error"
    tracking_mode:
      name: "${name} Tracking Mode"
    firmware_version:
      name: "${name} Firmware Version"
    device_type:
      name: "${name} Device Type"
    serial_number:
      name: "${name} Serial Number"

binary_sensor:
  - platform: victron
    victron_id: victron0
    load_state:
      name: "${name} Load State"
    relay_state:
      name: "${name} Relay State"
