substitutions:
  name: Victron-Smartshunt
  
esphome:
  name: victron-smartshunt
  platform: ESP8266
  board: d1_mini

external_components:
  - source: github://Martian-Dylan3/Victron_ESPHome@main
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
api:
logger:

uart:
  id: uart_0
  tx_pin: D7  # Not connected! The communication is read-only
  rx_pin: D8
  baud_rate: 19200
  stop_bits: 1
  data_bits: 8
  parity: NONE
  rx_buffer_size: 256

victron:
  uart_id: uart_0
  id: victron0
  #throttle: 10s

sensor:
  - platform: victron
    victron_id: victron0
    battery_voltage:
      name: "${name} Battery Voltage"
    auxiliary_battery_voltage:
      name: "${name} Auxiliary Battery Voltage"
    midpoint_voltage_of_the_battery_bank:
      name: "${name} Midpoint Voltage Of The Battery Bank"
    midpoint_deviation_of_the_battery_bank:
      name: "${name} Midpoint Deviation Of The Battery Bank"
    battery_current:
      name: "${name} Battery Current"
    battery_temperature:
      name: "${name} Battery Temperature"
    instantaneous_power:
      name: "${name} Instantaneous Power"
    consumed_amp_hours:
      name: "${name} Consumed Amp Hours"
    state_of_charge:
      name: "${name} State Of Charge"
    time_to_go:
      name: "${name} Time To Go"
    depth_of_the_deepest_discharge:
      name: "${name} Depth Of The Deepest Discharge"
    depth_of_the_last_discharge:
      name: "${name} Depth Of The Last Discharge"
    depth_of_the_average_discharge:
      name: "${name} Depth Of The Average Discharge"
    number_of_charge_cycles:
      name: "${name} Number Of Charge Cycles"
    number_of_full_discharges:
      name: "${name} Number Of Full Discharges"
    cumulative_amp_hours_drawn:
      name: "${name} Cumulative Amp Hours Drawn"
    min_battery_voltage:
      name: "${name} Min Battery Voltage"
    max_battery_voltage:
      name: "${name} Max Battery Voltage"
    last_full_charge:
      name: "${name} Last Full Charge"
    number_of_automatic_synchronizations:
      name: "${name} Number Of Automatic Synchronizations"
    number_of_low_main_voltage_alarms:
      name: "${name} Number Of Low Main Voltage Alarms"
    number_of_high_main_voltage_alarms:
      name: "${name} Number Of High Main Voltage Alarms"
    number_of_low_auxiliary_voltage_alarms:
      name: "${name} Number Of Low Auxiliary Voltage Alarms"
    number_of_high_auxiliary_voltage_alarms:
      name: "${name} Number Of High Auxiliary Voltage Alarms"
    min_auxiliary_battery_voltage:
      name: "${name} Min Auxiliary Battery Voltage"
    max_auxiliary_battery_voltage:
      name: "${name} Max Auxiliary Battery Voltage"
    amount_of_discharged_energy:
      name: "${name} Amount Of Discharged Energy"
    amount_of_charged_energy:
      name: "${name} Amount Of Charged Energy"
    dc_monitor_mode_id:
      name: "${name} DC Monitor Mode ID"

text_sensor:
  - platform: victron
    victron_id: victron0
    alarm_condition_active:
      name: "${name} Alarm Condition Active"
    alarm_reason:
      name: "${name} Alarm Reason"
    model_description:
      name: "${name} Model Description"
    firmware_version:
      name: "${name} Firmware Version"
    device_type:
      name: "${name} Device Type"
    serial_number:
      name: "${name} Serial Number"
    dc_monitor_mode:
      name: "${name} DC Monitor Mode"

binary_sensor:
  - platform: victron
    victron_id: victron0
    relay_state:
      name: "${name} Relay State"
