substitutions:
  device0: victron0
  device1: victron1

esphome:
  name: victron
  platform: ESP8266
  board: d1_mini

external_components:
  - source: github://Martian-Dylan3/Victron_ESPHome@main
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
api:
logger:

uart:
  - id: uart_0
    tx_pin: D7  # Not connected! The communication is read-only
    rx_pin: D8
    baud_rate: 19200
  stop_bits: 1
  data_bits: 8
  parity: NONE
  rx_buffer_size: 256

  - id: uart_1
    tx_pin: D6  # Not connected! The communication is read-only
    rx_pin: D5
    baud_rate: 19200
    stop_bits: 1
    data_bits: 8
    parity: NONE
    rx_buffer_size: 256

victron:
  - id: victron0
    uart_id: uart_0
    #throttle: 10s
  - id: victron1
    #uart_id: uart_1
    throttle: 10s

sensor:
  - platform: victron
    victron_id: victron0
    max_power_yesterday:
      name: "${device0} Max Power Yesterday"
    panel_voltage:
      name: "${device0} Panel Voltage"
    panel_power:
      name: "${device0} Panel Power"
    battery_current:
      name: "${device0} Panel Current"
    load_current:
      name: "${device0} Load Current"

  - platform: victron
    victron_id: victron1
    max_power_yesterday:
      name: "${device0} Max Power Yesterday"
    panel_voltage:
      name: "${device1} Panel Voltage"
    panel_power:
      name: "${device1} Panel Power"
    battery_current:
      name: "${device1} Panel Current"
    load_current:
      name: "${device1} Load Current"

text_sensor:
  - platform: victron
    victron_id: victron0
    charging_mode:
      name: "${device0} Charging Mode"
    error:
      name: "${device0} Error"
    tracking_mode:
      name: "${device0} Tracking Mode"

  - platform: victron
    victron_id: victron1
    charging_mode:
      name: "${device1} Charging Mode"
    error:
      name: "${device1} Error"
    tracking_mode:
      name: "${device1} Tracking Mode"
