esphome:
  name: victron-mppt
  platform: ESP8266
  board: d1_mini

external_components:
  - source: github://Martian-Dylan3/Victron_ESPHome@main
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
# api:

logger:
  baud_rate: 0
  esp8266_store_log_strings_in_flash: false

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

uart:
  id: uart_0
  tx_pin: D7  # Not connected! The communication is read-only
  rx_pin: D8  # Connect this this GPIO and GND to the MPPT charger
  baud_rate: 19200
  rx_buffer_size: 256

victron:
  uart_id: uart_0
  id: victron0
  throttle: 10s

sensor:
  - platform: victron
    victron_id: victron0
    max_power_yesterday:
      name: "victron-mppt max power yesterday"
    max_power_today:
      name: "victron-mppt max power today"
    yield_total:
      name: "victron-mppt yield total"
    yield_yesterday:
      name: "victron-mppt yield yesterday"
    yield_today:
      name: "victron-mppt yield today"
    panel_voltage:
      name: "victron-mppt panel voltage"
    panel_power:
      name: "victron-mppt panel power"
    battery_current:
      name: "victron-mppt panel current"
    battery_voltage:
      name: "victron-mppt battery voltage"
    day_number:
      name: "victron-mppt day number"
    charging_mode_id:
      name: "victron-mppt charging mode id"
    error_code:
      name: "victron-mppt error code"
    tracking_mode_id:
      name: "victron-mppt tracking mode id"
    load_current:
      name: "victron-mppt load current"

text_sensor:
  - platform: victron
    victron_id: victron0
    charging_mode:
      name: "victron-mppt charging mode"
    error:
      name: "victron-mppt error"
    tracking_mode:
      name: "victron-mppt tracking mode"
    firmware_version:
      name: "victron-mppt firmware version"
    device_type:
      name: "victron-mppt device type"
    serial_number:
      name: "victron-mppt serial number"

binary_sensor:
  - platform: victron
    victron_id: victron0
    load_state:
      name: "victron-mppt load state"
    relay_state:
      name: "$victron-mppt relay state"
